### ISSUE TITLE
Colorscheme not being consistent

### ISSUE THREAD

**Issue by truecelz** [cryptomilk/nightcity.nvim#5]
This is my config:
```lua
return {
	-- add colorscheme
	{
		"cryptomilk/nightcity.nvim",
		config = function()
			require("nightcity").setup({
				plugins = { default = true },
				styles = {
					afterlife = {
						red = "kabuki.red",
						yellow = "kabuki.yellow",
						orange = "kabuki.orange",
					},
				},
				on_highlights = function(groups)
					groups["Normal"] = { bg = "#000C15" }
					groups["NormalNC"] = { bg = "#000C15" } -- Normal Non-Current
					groups["NvimTreeNormal"] = { bg = "#000C15" } -- NerdTree
					groups["ToggleTerm"] = { bg = "#000C15" } -- ToggleTerm
					groups["TelescopeNormal"] = { bg = "#000C15" } -- Telescope
					-- Add more highlight groups as needed for other plugins
				end,
			})
		end,
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "nightcity-afterlife",
		},
	},
}
```
I am using Lazyvim (a nvim distro) and Lazy.nvim for plugin management

I changed my bg color to "000C15" for some reason, I tried setting the plugin bg colors manually since they weren't changing, but it still seems to keep the old bg color ONLY for plugins
![image](https://github.com/cryptomilk/nightcity.nvim/assets/171771931/825ce1aa-e629-4793-b2bd-caf17707ef67)
![image](https://github.com/cryptomilk/nightcity.nvim/assets/171771931/cc6dcd49-4d05-4473-8ee0-612d45404661)
sometimes it does work, but when I reopen the plugin, it always defaults to the stock bg color

**Comment by cryptomilk** [comment]
You might need to set `WinBar` and `vim.g.terminal_color_0` to your background color.

**Comment by truecelz** [comment]
Thank you, I love this theme btw :)
